'use strict';function v(h,a,b,c){h.A.dc(h.Sa,a,b,c,void 0)}function z(h,a,b,c){h.A.Ja?v(h,a,b,c):h.A.af()._OnMessageFromDOM({type:"event",component:h.Sa,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function A(h,a,b){h.A.B(h.Sa,a,b)}function B(h,a){for(const [b,c]of a)A(h,b,c)}function C(h){h.Jb||(h.A.Me(h.Td),h.Jb=!0)}window.La=class{constructor(h,a){this.A=h;this.Sa=a;this.Jb=!1;this.Td=()=>this.xa()}Yc(){}xa(){}};function D(h){-1!==h.Ia&&(self.clearTimeout(h.Ia),h.Ia=-1)}
window.De=class{constructor(h,a){this.Dc=h;this.ng=a;this.Ia=-1;this.Kb=-Infinity;this.Ud=()=>{this.Ia=-1;this.Kb=Date.now();this.Xa=!0;this.Dc();this.Xa=!1};this.Dd=this.Xa=!1}c(){D(this);this.Ud=this.Dc=null}};"use strict";function E(h,a){A(h,"get-element",b=>{const c=h.ca.get(b.elementId);return a(c,b)})}
window.Gg=class extends self.La{constructor(h,a){super(h,a);this.ca=new Map;this.Cc=!0;B(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const c=this.ca.get(b);this.Cc&&c.parentElement.removeChild(c);this.ca.delete(b)}}],["set-visible",b=>{this.Cc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Cc){var c=this.ca.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=
b.height+"px";b=b.fontSize;null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.xc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);E(this,b=>b)}xc(h){const a=this.ca.get(h.elementId);h.focus?a.focus():a.blur()}};"use strict";
{var F=function(q){return l.has(q)},G=function(q){return new Promise((e,k)=>{const m=new FileReader;m.onload=r=>e(r.target.result);m.onerror=r=>k(r);m.readAsArrayBuffer(q)})},H=async function(q){q=await G(q);return(new TextDecoder("utf-8")).decode(q)},I=function(q){if(q.xg){const e=document.createElement("script");e.async=!1;e.textContent=q.Ag;document.head.appendChild(e)}else return new Promise((e,k)=>{const m=document.createElement("script");m.onload=e;m.onerror=k;m.async=!1;m.src=q;document.head.appendChild(m)})};
const h=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=new Audio;const b={"audio/webm; codecs=opus":!!a.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!a.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!a.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!a.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!a.canPlayType("audio/mp4"),"audio/mpeg":!!a.canPlayType("audio/mpeg")};a=null;const c=[];let f=0;window.RealFile=
window.File;const p=[],t=new Map,d=new Map;let g=0;const n=[];self.Mg=function(q){if("function"!==typeof q)throw Error("runOnStartup called without a function");n.push(q)};const l=new Set(["cordova","playable-ad","instant-games"]);window.Pa=class q{constructor(e){this.Ja=e.Cg;this.ma=null;this.W="";this.Sc=e.zg;this.lb={};this.Ba=this.kb=null;this.Hb=[];this.Za=this.I=this.Ga=null;this.Fa=-1;this.sg=()=>this.yf();this.Ea=[];this.J=e.Vd;F(this.J)&&this.Ja&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.Ja=!1);this.Vc=!1;this.Mb=this.ha=null;"html5"!==this.J&&"playable-ad"!==this.J||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.hf(k));this.B("runtime","create-job-worker",()=>this.jf());"cordova"===this.J?document.addEventListener("deviceready",()=>this.rd(e)):this.rd(e)}c(){this.kc();this.ma&&
(this.ma=this.ma.onmessage=null);this.kb&&(this.kb.terminate(),this.kb=null);this.Ba&&(this.Ba.c(),this.Ba=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}ed(){return h&&"cordova"===this.J}qb(){return h&&F(this.J)||navigator.standalone}async rd(e){if("playable-ad"===this.J){this.ha=self.c3_base64files;this.Mb={};await this.Re();for(let m=0,r=e.Ka.length;m<r;++m){var k=e.Ka[m].toLowerCase();this.Mb.hasOwnProperty(k)?e.Ka[m]={xg:!0,Ag:this.Mb[k]}:this.ha.hasOwnProperty(k)&&(e.Ka[m]=
URL.createObjectURL(this.ha[k]))}}e.ug?this.W=e.ug:(k=location.origin,this.W=("null"===k?"file:///":k)+location.pathname,k=this.W.lastIndexOf("/"),-1!==k&&(this.W=this.W.substr(0,k+1)));if(e.Eg)for(const [m,r]of Object.entries(e.Eg))this.lb[m]=URL.createObjectURL(r);k=new MessageChannel;this.ma=k.port1;this.ma.onmessage=m=>this._OnMessageFromRuntime(m.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(m=>this.uf(m));this.Za=new self.ze(this);await this.Za.ve();this.fd();"object"===
typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.gg();this.Ja?await this.cf(e,k.port2):await this.bf(e,k.port2)}nc(e){return this.lb.hasOwnProperty(e)?this.lb[e]:e.endsWith("/workermain.js")&&this.lb.hasOwnProperty("workermain.js")?this.lb["workermain.js"]:"playable-ad"===this.J&&this.ha.hasOwnProperty(e.toLowerCase())?URL.createObjectURL(this.ha[e.toLowerCase()]):e}async Xb(e,k,m){if(e.startsWith("blob:"))return new Worker(e,
m);if(this.ed()&&"file:"===location.protocol)return e=await this.Wb(this.Sc+e),new Worker(URL.createObjectURL(new Blob([e],{type:"application/javascript"})),m);e=new URL(e,k);if(location.origin!==e.origin){e=await fetch(e);if(!e.ok)throw Error("failed to fetch worker script");e=await e.blob();return new Worker(URL.createObjectURL(e),m)}return new Worker(e,m)}fd(){if(this.qb()){const e=document.documentElement.style,k=document.body.style,m=window.innerWidth<window.innerHeight,r=m?window.screen.width:
window.screen.height;k.height=e.height=(m?window.screen.height:window.screen.width)+"px";k.width=e.width=r+"px"}}qd(e){return{baseUrl:this.W,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:q.cc(),projectData:e.Lg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:e.Vd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Kg,jobScheduler:this.Za.te(),
supportedAudioFormats:b,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Sc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Sc+"opus.wasm.wasm",isiOSCordova:this.ed(),isiOSWebView:this.qb(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async cf(e,k){var m=this.nc(e.Dg);this.kb=await this.Xb(m,this.W,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";m=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=
this.I;this.kb.postMessage(Object.assign(this.qd(e),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:m,workerDependencyScripts:e.Xc||[],engineScripts:e.Ka,projectScripts:window.Jg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,m,...this.Za.ue()]);this.Hb=p.map(r=>new r(this));this.pd();self.c3_callFunction=(r,u)=>this.Ga.df(r,u);"preview"===this.J&&(self.goToLastErrorScript=()=>this.dc("runtime","go-to-last-error-script"))}async bf(e,k){this.I=document.createElement("canvas");this.I.style.display=
"none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Hb=p.map(r=>new r(this));this.pd();const m=e.Ka.map(r=>"string"===typeof r?(new URL(r,this.W)).toString():r);Array.isArray(e.Xc)&&m.unshift(...e.Xc);await Promise.all(m.map(r=>I(r)));if(e.Wd&&0<e.Wd.length){const r=self.C3_ProjectScriptsStatus;try{if(await Promise.all(e.Wd.map(u=>I(u[1]))),Object.values(r).some(u=>!u)){self.setTimeout(()=>this.yd(r),100);return}}catch(u){console.error("[Preview] Error loading project scripts: ",
u);self.setTimeout(()=>this.yd(r),100);return}}"preview"===this.J&&"object"!==typeof self.Fg.Hg?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(e=Object.assign(this.qd(e),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:n}),this.Ba=self.C3_CreateRuntime(e),await self.C3_InitRuntime(this.Ba,e))}yd(e){e=
`Failed to load project script '${Object.entries(e).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+e);alert(e)}async jf(){const e=await this.Za.od();return{outputPort:e,transferables:[e]}}af(){if(this.Ja)throw Error("not available in worker mode");return this.Ba}dc(e,k,m,r,u){this.ma.postMessage({type:"event",component:e,handler:k,dispatchOpts:r||null,data:m,responseId:null},this.Vc?void 0:u)}gd(e,k,m,r,u){const x=g++,w=new Promise((y,
Q)=>{d.set(x,{resolve:y,reject:Q})});this.ma.postMessage({type:"event",component:e,handler:k,dispatchOpts:r||null,data:m,responseId:x},this.Vc?void 0:u);return w}["_OnMessageFromRuntime"](e){const k=e.type;if("event"===k)return this.pf(e);if("result"===k)this.Bf(e);else if("runtime-ready"===k)this.Cf();else if("alert"===k)alert(e.message);else throw Error(`unknown message '${k}'`);}pf(e){const k=e.component,m=e.handler,r=e.data,u=e.responseId;if(e=t.get(k))if(e=e.get(m)){var x=null;try{x=e(r)}catch(w){console.error(`Exception in '${k}' handler '${m}':`,
w);null!==u&&this.Ab(u,!1,""+w);return}if(null===u)return x;x&&x.then?x.then(w=>this.Ab(u,!0,w)).catch(w=>{console.error(`Rejection from '${k}' handler '${m}':`,w);this.Ab(u,!1,""+w)}):this.Ab(u,!0,x)}else console.warn(`[DOM] No handler '${m}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ab(e,k,m){let r;m&&m.transferables&&(r=m.transferables);this.ma.postMessage({type:"result",responseId:e,isOk:k,result:m},r)}Bf(e){const k=e.responseId,m=e.isOk;e=e.result;
const r=d.get(k);m?r.resolve(e):r.reject(e);d.delete(k)}B(e,k,m){let r=t.get(e);r||(r=new Map,t.set(e,r));if(r.has(k))throw Error(`[DOM] Component '${e}' already has handler '${k}'`);r.set(k,m)}static mb(e){if(p.includes(e))throw Error("DOM handler already added");p.push(e)}pd(){for(const e of this.Hb)if("runtime"===e.Sa){this.Ga=e;return}throw Error("cannot find runtime DOM handler");}uf(e){this.dc("debugger","message",e)}Cf(){for(const e of this.Hb)e.Yc()}static cc(){return!!(document.fullscreenElement||
document.webkitFullscreenElement||document.mozFullScreenElement)}Me(e){this.Ea.push(e);this.Ac()}Nf(e){e=this.Ea.indexOf(e);if(-1===e)throw Error("invalid callback");this.Ea.splice(e,1);this.Ea.length||this.kc()}Ac(){-1===this.Fa&&this.Ea.length&&(this.Fa=requestAnimationFrame(this.sg))}kc(){-1!==this.Fa&&(cancelAnimationFrame(this.Fa),this.Fa=-1)}yf(){this.Fa=-1;for(const e of this.Ea)e();this.Ac()}qa(e){this.Ga.qa(e)}wa(e){this.Ga.wa(e)}zc(){this.Ga.zc()}tb(e){this.Ga.tb(e)}xe(){return!!b["audio/webm; codecs=opus"]}async lg(e){e=
await this.gd("runtime","opus-decode",{arrayBuffer:e},null,[e]);return new Float32Array(e)}we(e){return/^(?:[a-z]+:)?\/\//.test(e)||"data:"===e.substr(0,5)||"blob:"===e.substr(0,5)}ye(e){return!this.we(e)}async hf(e){const k=e.filename;switch(e.as){case "text":return await this.me(k);case "buffer":return await this.Wb(k);default:throw Error("unsupported type");}}ad(e){const k=window.cordova.file.applicationDirectory+"www/"+e.toLowerCase();return new Promise((m,r)=>{window.resolveLocalFileSystemURL(k,
u=>{u.file(m,r)},r)})}async me(e){e=await this.ad(e);return await H(e)}lc(){if(c.length&&!(8<=f)){f++;var e=c.shift();this.Se(e.filename,e.Bg,e.wg)}}Wb(e){return new Promise((k,m)=>{c.push({filename:e,Bg:r=>{f--;this.lc();k(r)},wg:r=>{f--;this.lc();m(r)}});this.lc()})}async Se(e,k,m){try{const r=await this.ad(e),u=await G(r);k(u)}catch(r){m(r)}}async Re(){const e=[];for(const [k,m]of Object.entries(this.ha))e.push(this.Qe(k,m));await Promise.all(e)}async Qe(e,k){if("object"===typeof k)this.ha[e]=
new Blob([k.str],{type:k.type}),this.Mb[e]=k.str;else{let m=await this.Ze(k);m||(m=this.Ue(k));this.ha[e]=m}}async Ze(e){try{return await (await fetch(e)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Ue(e){e=this.Hf(e);return this.Pe(e.data,e.yg)}Hf(e){var k=e.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");
var m=e.substring(k+1);k=e.substring(5,k).split(";");e=k[0]||"";const r=k[2];m="base64"===k[1]||"base64"===r?atob(m):decodeURIComponent(m);return{yg:e,data:m}}Pe(e,k){var m=e.length;let r=m>>2,u=new Uint8Array(m),x=new Uint32Array(u.buffer,0,r),w,y;for(y=w=0;w<r;++w)x[w]=e.charCodeAt(y++)|e.charCodeAt(y++)<<8|e.charCodeAt(y++)<<16|e.charCodeAt(y++)<<24;for(m&=3;m--;)u[y]=e.charCodeAt(y),++y;return new Blob([u],{type:k})}gg(){let e=null;const k=new Promise(u=>e=u),m=new ArrayBuffer(1),r=new MessageChannel;
r.port2.onmessage=u=>{u.data&&u.data.arrayBuffer||(this.Vc=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));e()};r.port1.postMessage({arrayBuffer:m},[m]);return k}}}"use strict";
{var K=function(){const d=document.activeElement;if(!d)return!1;const g=d.tagName.toLowerCase(),n=new Set("email number password search tel text url".split(" "));return"textarea"===g?!0:"input"===g?n.has(d.type.toLowerCase()||"text"):J(d)},L=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(d){return!1}},M=function(d){(d.metaKey||d.ctrlKey)&&d.preventDefault()},N=function(d){p.has(d.target.tagName.toLowerCase())&&d.preventDefault()},J=function(d){do{if(d.parentNode&&d.hasAttribute("contenteditable"))return!0;
d=d.parentNode}while(d);return!1},R=async function(d,g,n){if(!/firefox/i.test(navigator.userAgent))return await O(d);var l=await P(d);l=(new DOMParser).parseFromString(l,"image/svg+xml");const q=l.documentElement;if(q.hasAttribute("width")&&q.hasAttribute("height")){const e=q.getAttribute("width"),k=q.getAttribute("height");if(!e.includes("%")&&!k.includes("%"))return await O(d)}q.setAttribute("width",g+"px");q.setAttribute("height",n+"px");l=(new XMLSerializer).serializeToString(l);d=new Blob([l],
{type:"image/svg+xml"});return await O(d)},P=function(d){return new Promise((g,n)=>{let l=new FileReader;l.onload=q=>g(q.target.result);l.onerror=q=>n(q);l.readAsText(d)})},O=async function(d){d=URL.createObjectURL(d);try{return await S(d)}finally{URL.revokeObjectURL(d)}},S=function(d){return new Promise((g,n)=>{const l=new Image;l.onload=()=>g(l);l.onerror=q=>n(q);l.src=d})},T=function(d){return new Promise((g,n)=>{const l=document.createElement("link");l.onload=()=>g(l);l.onerror=q=>n(q);l.rel=
"stylesheet";l.href=d;document.head.appendChild(l)})},U=function(d){return d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents||d.originalEvent&&d.originalEvent.sourceCapabilities&&d.originalEvent.sourceCapabilities.firesTouchEvents};const h=self.Pa,a=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),b={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},c={dispatchUserScriptEvent:!0},f={dispatchRuntimeEvent:!0},p=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(d){d=
await O(d);if(0<d.width&&0<d.height)return[d.width,d.height];{d.style.position="absolute";d.style.left="0px";d.style.top="0px";d.style.visibility="hidden";document.body.appendChild(d);const g=d.getBoundingClientRect();document.body.removeChild(d);return[g.width,g.height]}};self.C3_RasterSvgImageBlob=async function(d,g,n,l,q){d=await R(d,g,n);const e=document.createElement("canvas");e.width=l;e.height=q;e.getContext("2d").drawImage(d,0,0,g,n);return e};let t=!1;document.addEventListener("pause",()=>
t=!0);document.addEventListener("resume",()=>t=!1);h.mb(class extends self.La{constructor(d){super(d,"runtime");this.Id=!0;this.Ha=-1;this.Tc="any";this.zd=this.Ad=!1;this.Mc=this.hb=this.sa=null;d.B("canvas","update-size",l=>this.Ff(l));d.B("runtime","invoke-download",l=>this.sf(l));d.B("runtime","raster-svg-image",l=>this.zf(l));d.B("runtime","get-svg-image-size",l=>this.rf(l));d.B("runtime","set-target-orientation",l=>this.Df(l));d.B("runtime","register-sw",()=>this.Af());d.B("runtime","post-to-debugger",
l=>this.ud(l));d.B("runtime","go-to-script",l=>this.ud(l));d.B("runtime","before-start-ticking",()=>this.gf());d.B("runtime","debug-highlight",l=>this.kf(l));d.B("runtime","enable-device-orientation",()=>this.Oe());d.B("runtime","enable-device-motion",()=>this.Ne());d.B("runtime","add-stylesheet",l=>this.ff(l));d.B("runtime","alert",l=>this.rc(l));const g=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",l=>{const q=l.target;g.has(q.tagName.toLowerCase())||J(q)||l.preventDefault()});
const n=d.I;window.addEventListener("selectstart",N);window.addEventListener("gesturehold",N);n.addEventListener("selectstart",N);n.addEventListener("gesturehold",N);window.addEventListener("touchstart",N,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",N,{passive:!1}),n.addEventListener("pointerdown",N)):n.addEventListener("touchstart",N);this.eb=0;window.addEventListener("mousedown",l=>{1===l.button&&l.preventDefault()});window.addEventListener("mousewheel",
M,{passive:!1});window.addEventListener("wheel",M,{passive:!1});window.addEventListener("resize",()=>this.Gf());d.qb()&&window.addEventListener("focusout",()=>{K()||(document.scrollingElement.scrollTop=0)});this.Ca=new Set;this.Nb=new WeakSet;this.la=!1}gf(){"cordova"===this.A.J?(document.addEventListener("pause",()=>this.yc(!0)),document.addEventListener("resume",()=>this.yc(!1))):document.addEventListener("visibilitychange",()=>this.yc(document.hidden));return{isSuspended:!(!document.hidden&&!t)}}Yc(){window.addEventListener("focus",
()=>this.Bb("window-focus"));window.addEventListener("blur",()=>{this.Bb("window-blur",{parentHasFocus:L()});this.eb=0});window.addEventListener("fullscreenchange",()=>this.tc());window.addEventListener("webkitfullscreenchange",()=>this.tc());window.addEventListener("mozfullscreenchange",()=>this.tc());window.addEventListener("fullscreenerror",g=>this.uc(g));window.addEventListener("webkitfullscreenerror",g=>this.uc(g));window.addEventListener("mozfullscreenerror",g=>this.uc(g));window.addEventListener("keydown",
g=>this.td("keydown",g));window.addEventListener("keyup",g=>this.td("keyup",g));window.addEventListener("dblclick",g=>this.vc("dblclick",g,b));window.addEventListener("wheel",g=>this.wf(g));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",g=>{this.oc(g);this.Qa("pointerdown",g)}),this.A.Ja&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.hb=new self.De(()=>this.Xe(),5),this.hb.Dd=!0,window.addEventListener("pointerrawupdate",g=>this.xf(g))):window.addEventListener("pointermove",
g=>this.Qa("pointermove",g)),window.addEventListener("pointerup",g=>this.Qa("pointerup",g)),window.addEventListener("pointercancel",g=>this.Qa("pointercancel",g))):(window.addEventListener("mousedown",g=>{this.oc(g);this.wc("pointerdown",g)}),window.addEventListener("mousemove",g=>this.wc("pointermove",g)),window.addEventListener("mouseup",g=>this.wc("pointerup",g)),window.addEventListener("touchstart",g=>{this.oc(g);this.zb("pointerdown",g)}),window.addEventListener("touchmove",g=>this.zb("pointermove",
g)),window.addEventListener("touchend",g=>this.zb("pointerup",g)),window.addEventListener("touchcancel",g=>this.zb("pointercancel",g)));const d=()=>this.zc();window.addEventListener("pointerup",d,!0);window.addEventListener("touchend",d,!0);window.addEventListener("click",d,!0);window.addEventListener("keydown",d,!0);window.addEventListener("gamepadconnected",d,!0)}Bb(d,g){v(this,d,g||null,f)}xb(){return Math.max(window.innerWidth,1)}wb(){return Math.max(window.innerHeight,1)}Gf(){const d=this.xb(),
g=this.wb();this.Bb("window-resize",{innerWidth:d,innerHeight:g,devicePixelRatio:window.devicePixelRatio});this.A.qb()&&(-1!==this.Ha&&clearTimeout(this.Ha),this.vd(d,g,0))}Of(d,g,n){-1!==this.Ha&&clearTimeout(this.Ha);this.Ha=setTimeout(()=>this.vd(d,g,n),48)}vd(d,g,n){const l=this.xb(),q=this.wb();this.Ha=-1;l!=d||q!=g?this.Bb("window-resize",{innerWidth:l,innerHeight:q,devicePixelRatio:window.devicePixelRatio}):10>n&&this.Of(l,q,n+1)}Df(d){this.Tc=d.targetOrientation}hg(){const d=this.Tc;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(d).catch(g=>console.warn("[Construct 3] Failed to lock orientation: ",g));else try{let g=!1;screen.lockOrientation?g=screen.lockOrientation(d):screen.webkitLockOrientation?g=screen.webkitLockOrientation(d):screen.mozLockOrientation?g=screen.mozLockOrientation(d):screen.msLockOrientation&&(g=screen.msLockOrientation(d));g||console.warn("[Construct 3] Failed to lock orientation")}catch(g){console.warn("[Construct 3] Failed to lock orientation: ",g)}}tc(){const d=
h.cc();d&&"any"!==this.Tc&&this.hg();v(this,"fullscreenchange",{isFullscreen:d,innerWidth:this.xb(),innerHeight:this.wb()})}uc(d){console.warn("[Construct 3] Fullscreen request failed: ",d);v(this,"fullscreenerror",{isFullscreen:h.cc(),innerWidth:this.xb(),innerHeight:this.wb()})}yc(d){d?this.A.kc():this.A.Ac();v(this,"visibilitychange",{hidden:d})}td(d,g){"Backspace"===g.key&&N(g);const n=a.get(g.code)||g.code;z(this,d,{code:n,key:g.key,which:g.which,repeat:g.repeat,altKey:g.altKey,ctrlKey:g.ctrlKey,
metaKey:g.metaKey,shiftKey:g.shiftKey,timeStamp:g.timeStamp},b)}wf(d){v(this,"wheel",{clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,deltaX:d.deltaX,deltaY:d.deltaY,deltaZ:d.deltaZ,deltaMode:d.deltaMode,timeStamp:d.timeStamp},b)}vc(d,g,n){U(g)||z(this,d,{button:g.button,buttons:g.buttons,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,timeStamp:g.timeStamp},n)}wc(d,g){if(!U(g)){var n=this.eb;"pointerdown"===d&&0!==n?d="pointermove":"pointerup"===d&&0!==g.buttons&&
(d="pointermove");z(this,d,{pointerId:1,pointerType:"mouse",button:g.button,buttons:g.buttons,lastButtons:n,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:g.timeStamp},b);this.eb=g.buttons;this.vc(g.type,g,c)}}Qa(d,g){if(this.hb&&"pointermove"!==d){var n=this.hb;n.Xa||(D(n),n.Kb=Date.now())}n=0;"mouse"===g.pointerType&&(n=this.eb);z(this,d,{pointerId:g.pointerId,pointerType:g.pointerType,button:g.button,
buttons:g.buttons,lastButtons:n,clientX:g.clientX,clientY:g.clientY,pageX:g.pageX,pageY:g.pageY,width:g.width||0,height:g.height||0,pressure:g.pressure||0,tangentialPressure:g.tangentialPressure||0,tiltX:g.tiltX||0,tiltY:g.tiltY||0,twist:g.twist||0,timeStamp:g.timeStamp},b);"mouse"===g.pointerType&&(n="mousemove","pointerdown"===d?n="mousedown":"pointerup"===d&&(n="pointerup"),this.vc(n,g,c),this.eb=g.buttons)}xf(d){this.Mc=d;d=this.hb;if(-1===d.Ia){var g=Date.now(),n=g-d.Kb,l=d.ng;n>=l&&d.Dd?(d.Kb=
g,d.Xa=!0,d.Dc(),d.Xa=!1):d.Ia=self.setTimeout(d.Ud,Math.max(l-n,4))}}Xe(){this.Qa("pointermove",this.Mc);this.Mc=null}zb(d,g){for(let n=0,l=g.changedTouches.length;n<l;++n){const q=g.changedTouches[n];z(this,d,{pointerId:q.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:q.clientX,clientY:q.clientY,pageX:q.pageX,pageY:q.pageY,width:2*(q.radiusX||q.webkitRadiusX||0),height:2*(q.radiusY||q.webkitRadiusY||0),pressure:q.force||q.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,
twist:q.rotationAngle||0,timeStamp:g.timeStamp},b)}}oc(d){window!==window.top&&window.focus();this.sd(d.target)&&document.activeElement&&!this.sd(document.activeElement)&&document.activeElement.blur()}sd(d){return!d||d===document||d===window||d===document.body||"canvas"===d.tagName.toLowerCase()}Oe(){this.Ad||(this.Ad=!0,window.addEventListener("deviceorientation",d=>this.mf(d)),window.addEventListener("deviceorientationabsolute",d=>this.nf(d)))}Ne(){this.zd||(this.zd=!0,window.addEventListener("devicemotion",
d=>this.lf(d)))}mf(d){v(this,"deviceorientation",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp,webkitCompassHeading:d.webkitCompassHeading,webkitCompassAccuracy:d.webkitCompassAccuracy},b)}nf(d){v(this,"deviceorientationabsolute",{absolute:!!d.absolute,alpha:d.alpha||0,beta:d.beta||0,gamma:d.gamma||0,timeStamp:d.timeStamp},b)}lf(d){let g=null;var n=d.acceleration;n&&(g={x:n.x||0,y:n.y||0,z:n.z||0});n=null;var l=d.accelerationIncludingGravity;l&&(n={x:l.x||
0,y:l.y||0,z:l.z||0});l=null;const q=d.rotationRate;q&&(l={alpha:q.alpha||0,beta:q.beta||0,gamma:q.gamma||0});v(this,"devicemotion",{acceleration:g,accelerationIncludingGravity:n,rotationRate:l,interval:d.interval,timeStamp:d.timeStamp},b)}Ff(d){const g=this.A,n=g.I;n.style.width=d.styleWidth+"px";n.style.height=d.styleHeight+"px";n.style.marginLeft=d.marginLeft+"px";n.style.marginTop=d.marginTop+"px";g.fd();this.Id&&(n.style.display="",this.Id=!1)}sf(d){const g=d.url;d=d.filename;const n=document.createElement("a"),
l=document.body;n.textContent=d;n.href=g;n.download=d;l.appendChild(n);n.click();l.removeChild(n)}async zf(d){var g=d.imageBitmapOpts;d=await self.C3_RasterSvgImageBlob(d.blob,d.imageWidth,d.imageHeight,d.surfaceWidth,d.surfaceHeight);g=g?await createImageBitmap(d,g):await createImageBitmap(d);return{imageBitmap:g,transferables:[g]}}async rf(d){return await self.C3_GetSvgImageSize(d.blob)}async ff(d){await T(d.url)}zc(){var d=[...this.Ca];this.Ca.clear();if(!this.la)for(const g of d)(d=g.play())&&
d.catch(()=>{this.Nb.has(g)||this.Ca.add(g)})}qa(d){if("function"!==typeof d.play)throw Error("missing play function");this.Nb.delete(d);let g;try{g=d.play()}catch(n){this.Ca.add(d);return}g&&g.catch(()=>{this.Nb.has(d)||this.Ca.add(d)})}wa(d){this.Ca.delete(d);this.Nb.add(d)}tb(d){this.la=!!d}kf(d){if(d.show){this.sa||(this.sa=document.createElement("div"),this.sa.id="inspectOutline",document.body.appendChild(this.sa));var g=this.sa;g.style.display="";g.style.left=d.left-1+"px";g.style.top=d.top-
1+"px";g.style.width=d.width+2+"px";g.style.height=d.height+2+"px";g.textContent=d.name}else this.sa&&(this.sa.style.display="none")}Af(){window.C3_RegisterSW&&window.C3_RegisterSW()}ud(d){window.c3_postToMessagePort&&(d.from="runtime",window.c3_postToMessagePort(d))}df(d,g){return this.A.gd(this.Sa,"js-invoke-function",{name:d,params:g},void 0,void 0)}rc(d){alert(d.message)}})}"use strict";
{const h=document.currentScript.src;self.ze=class{constructor(a){this.Rb=a;this.W=h?h.substr(0,h.lastIndexOf("/")+1):a.W;this.pg=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Jd=[];this.Qc=this.Jc=null}async ve(){if(this.mg)throw Error("already initialised");this.mg=!0;var a=this.Rb.nc("dispatchworker.js");this.Fc=await this.Rb.Xb(a,this.W,{name:"DispatchWorker"});a=new MessageChannel;this.Jc=a.port1;this.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);this.Qc=await this.od()}async od(){const a=
this.Jd.length;var b=this.Rb.nc("jobworker.js");b=await this.Rb.Xb(b,this.W,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;this.Fc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);this.Jd.push(b);return f.port1}te(){return{inputPort:this.Jc,outputPort:this.Qc,maxNumWorkers:this.pg}}ue(){return[this.Jc,this.Qc]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Pa({Cg:"undefined"!==typeof OffscreenCanvas,Dg:"workermain.js",Ka:["scripts/c3runtime.js"],zg:"scripts/",Xc:[],Vd:"html5"}));"use strict";
{const h=180/Math.PI;self.da=class extends self.La{constructor(a){super(a,"audio");this.Gb=this.f=null;this.Ib=this.Ic=!1;this.na=()=>this.ig();this.aa=[];this.C=[];this.ga=null;this.Kd="";this.Ld=-1;this.gb=new Map;this.Nc=1;this.la=!1;this.Uc=0;this.Tb=1;this.Gc=0;this.Nd="HRTF";this.Ed="inverse";this.Od=600;this.Md=1E4;this.Qd=1;this.Gd=this.Rc=!1;this.tg=this.A.xe();this.ba=new Map;this.za=new Set;this.Kc=!1;this.Oc="";this.ta=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.vf(b,c);this.Fb=null;
self.C3Audio_GetOutputStream=()=>this.qf();self.C3Audio_DOMInterface=this;B(this,[["create-audio-context",b=>this.Te(b)],["play",b=>this.If(b)],["stop",b=>this.eg(b)],["stop-all",()=>this.fg()],["set-paused",b=>this.Yf(b)],["set-volume",b=>this.cg(b)],["fade-volume",b=>this.Ye(b)],["set-master-volume",b=>this.Wf(b)],["set-muted",b=>this.Xf(b)],["set-silent",b=>this.$f(b)],["set-looping",b=>this.Vf(b)],["set-playback-rate",b=>this.Zf(b)],["seek",b=>this.Pf(b)],["preload",b=>this.Jf(b)],["unload",b=>
this.jg(b)],["unload-all",()=>this.kg()],["set-suspended",b=>this.ag(b)],["add-effect",b=>this.md(b)],["set-effect-param",b=>this.Sf(b)],["remove-effects",b=>this.Lf(b)],["tick",b=>this.Ef(b)],["load-state",b=>this.tf(b)]])}async Te(a){a.isiOSCordova&&(this.Rc=!0);this.Uc=a.timeScaleMode;this.Nd=["equalpower","HRTF","soundfield"][a.panningModel];this.Ed=["linear","inverse","exponential"][a.distanceModel];this.Od=a.refDistance;this.Md=a.maxDistance;this.Qd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.nd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.nd()};this.Gb=this.f.createGain();this.Gb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.Yb();try{await Promise.all(a.preloadList.map(c=>
this.vb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}nd(){this.Ib||(this.Ic=!1,window.addEventListener("pointerup",this.na,!0),window.addEventListener("touchend",this.na,!0),window.addEventListener("click",this.na,!0),window.addEventListener("keydown",this.na,!0),this.Ib=!0)}Ve(){this.Ib&&(this.Ic=!0,window.removeEventListener("pointerup",this.na,!0),window.removeEventListener("touchend",this.na,!0),window.removeEventListener("click",
this.na,!0),window.removeEventListener("keydown",this.na,!0),this.Ib=!1)}ig(){if(!this.Ic){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.Ve()}}V(){return this.f}Yb(){return this.f.currentTime}oa(){return this.Gb}cd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].O():this.oa()}Xd(a,b){a=a.toLowerCase();let c=this.ba.get(a);c||(c=[],this.ba.set(a,c));b.Uf(c.length);
b.bg(a);c.push(b);this.xd(a)}xd(a){let b=this.oa();const c=this.ba.get(a);if(c&&c.length){b=c[0].O();for(let f=0,p=c.length;f<p;++f){const t=c[f];f+1===p?t.R(this.oa()):t.R(c[f+1].O())}}for(const f of this.ja(a))f.Ee(b);this.ta&&this.Oc===a&&(this.ta.disconnect(),this.ta.connect(b))}ob(){return this.Nc}pb(){return this.la}Tf(){this.Gd=!0}oe(a,b){return b?this.A.lg(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):new Promise((c,f)=>{this.f.decodeAudioData(a,
c,f)})}qa(a){this.A.qa(a)}wa(a){this.A.wa(a)}hd(a){let b=0;for(let c=0,f=this.C.length;c<f;++c){const p=this.C[c];this.C[b]=p;p.K===a?p.c():++b}this.C.length=b}Fe(){let a=0;for(let b=0,c=this.aa.length;b<c;++b){const f=this.aa[b];this.aa[a]=f;f.pa()?f.c():++a}this.aa.length=a}*ja(a){if(a)for(const b of this.C)self.da.pe(b.Z,a)&&(yield b);else this.ga&&!this.ga.S()&&(yield this.ga)}async vb(a,b,c,f,p){for(const t of this.aa)if(t.Na()===b)return await V(t),t;if(p)return null;f&&(this.Rc||this.Gd)&&
this.Fe();p="audio/webm; codecs=opus"===c&&!this.tg;f&&p&&this.Tf();a=!f||this.Rc||p?new self.ke(this,a,b,c,f,p):new self.ie(this,a,b,c,f);this.aa.push(a);await V(a);return a}async mc(a,b,c,f,p){for(const t of this.C)if(t.Na()===b&&(t.Vb()||p))return t.He(f),t;a=await this.vb(a,b,c,p);f="html5"===a.Bc?new self.je(a.i,a,f):new self.le(a.i,a,f);this.C.push(f);return f}Le(a){let b=this.gb.get(a);if(!b){let c=null;b={Wc:0,promise:new Promise(f=>c=f),resolve:c};this.gb.set(a,b)}b.Wc++}Mf(a){const b=this.gb.get(a);
if(!b)throw Error("expected pending tag");b.Wc--;0===b.Wc&&(b.resolve(),this.gb.delete(a))}jc(a){a||(a=this.Kd);return(a=this.gb.get(a))?a.promise:Promise.resolve()}yb(){if(0<this.za.size)C(this);else for(const a of this.C)if(a.dd()){C(this);break}}xa(){for(var a of this.za)a.xa();a=this.Yb();for(var b of this.C)b.xa(a);b=this.C.filter(c=>c.dd()).map(c=>c.Ma());v(this,"state",{tickCount:this.Ld,audioInstances:b,analysers:[...this.za].map(c=>c.re())});0===b.length&&0===this.za.size&&this.Jb&&(this.A.Nf(this.Td),
this.Jb=!1)}ec(a,b,c){v(this,"trigger",{type:a,tag:b,aiid:c})}async If(a){const b=a.originalUrl,c=a.url,f=a.type,p=a.isMusic,t=a.tag,d=a.isLooping,g=a.vol,n=a.pos,l=a.panning;let q=a.off;0<q&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),q=q-a.performanceTime/1E3+a.contextTime):q=q-performance.now()/1E3+this.f.currentTime);this.Kd=t;this.Le(t);try{this.ga=await this.mc(b,c,f,t,p),l?(this.ga.sb(!0),this.ga.Ge(l.x,l.y,l.angle,l.innerAngle,l.outerAngle,l.outerGain),l.hasOwnProperty("uid")&&
this.ga.Ie(l.uid)):this.ga.sb(!1),this.ga.Play(d,g,n,q)}catch(e){console.error("[Construct 3] Audio: error starting playback: ",e);return}finally{this.Mf(t)}C(this)}eg(a){a=a.tag;for(const b of this.ja(a))b.ka()}fg(){for(const a of this.C)a.ka()}Yf(a){const b=a.tag;a=a.paused;for(const c of this.ja(b))a?c.Oa():c.rb();this.yb()}cg(a){const b=a.tag;a=a.vol;for(const c of this.ja(b))c.ub(a)}async Ye(a){const b=a.tag,c=a.vol,f=a.duration;a=a.stopOnEnd;await this.jc(b);for(const p of this.ja(b))p.qe(c,
f,a);this.yb()}Wf(a){this.Nc=a.vol;for(const b of this.C)b.Db()}Xf(a){const b=a.tag;a=a.isMuted;for(const c of this.ja(b))c.jd(a)}$f(a){this.la=a.isSilent;this.A.tb(this.la);for(const b of this.C)b.Cb()}Vf(a){const b=a.tag;a=a.isLooping;for(const c of this.ja(b))c.hc(a)}async Zf(a){const b=a.tag;a=a.rate;await this.jc(b);for(const c of this.ja(b))c.ld(a)}async Pf(a){const b=a.tag;a=a.pos;await this.jc(b);for(const c of this.ja(b))c.fc(a)}async Jf(a){const b=a.originalUrl,c=a.url,f=a.type;a=a.isMusic;
try{await this.mc(b,c,f,"",a)}catch(p){console.error("[Construct 3] Audio: error preloading: ",p)}}async jg(a){if(a=await this.vb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}kg(){for(const a of this.aa)a.c();this.aa.length=0}ag(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.ic(a);a&&this.f.suspend&&this.f.suspend()}Ef(a){this.Tb=a.timeScale;this.Gc=a.gameTime;this.Ld=a.tickCount;if(0!==this.Uc)for(var b of this.C)b.ya();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.C)f.fa===a&&f.kd(c.x,c.y,c.angle)}}async md(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.ce(this,...f);else if("delay"===b)f=new self.ae(this,...f);else if("convolution"===b){b=null;try{b=await this.vb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(p){console.log("[Construct 3] Audio: error loading convolution: ",p);return}f=new self.$d(this,b.$,...f);f.Qf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)f=new self.de(this,...f);else if("phaser"===b)f=new self.fe(this,...f);else if("gain"===b)f=new self.ee(this,...f);else if("tremolo"===b)f=new self.he(this,...f);else if("ringmod"===b)f=new self.ge(this,...f);else if("distortion"===b)f=new self.be(this,...f);else if("compressor"===b)f=new self.Zd(this,...f);else if("analyser"===b)f=new self.Yd(this,...f);else throw Error("invalid effect type");this.Xd(c,f);this.wd()}Sf(a){const b=a.index,c=a.param,f=a.value,p=a.ramp,
t=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,f,p,t),this.wd())}Lf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const c of b)c.c();this.ba.delete(a);this.xd(a)}}Ke(a){this.za.add(a);this.yb()}Kf(a){this.za.delete(a)}wd(){this.Kc||(this.Kc=!0,Promise.resolve().then(()=>this.We()))}We(){const a={};for(const [b,c]of this.ba)a[b]=c.map(f=>f.Ma());v(this,"fxstate",{fxstate:a});this.Kc=!1}async tf(a){const b=a.saveLoadMode;if(3!==b)for(var c of this.C)c.pa()&&1===
b||(c.pa()||2!==b)&&c.ka();for(const f of this.ba.values())for(const p of f)p.c();this.ba.clear();this.Tb=a.timeScale;this.Gc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.la=a.isSilent;this.A.tb(this.la);this.Nc=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(p=>this.md(p))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.ef(f,b)));this.yb()}async ef(a,b){if(3!==b){var c=a.bufferOriginalUrl,f=a.bufferUrl,p=a.bufferType,
t=a.isMusic,d=a.tag,g=a.isLooping,n=a.volume,l=a.playbackTime;if(!t||1!==b)if(t||2!==b){b=null;try{b=await this.mc(c,f,p,d,t)}catch(q){console.error("[Construct 3] Audio: error loading audio state: ",q);return}b.Ce(a.pan);b.Play(g,n,l,0);a.isPlaying||b.Oa();b.qc(a)}}}vf(a,b){this.ta&&this.ta.disconnect();this.Oc=b.toLowerCase();this.ta=this.f.createMediaStreamSource(a);this.ta.connect(this.cd(this.Oc))}qf(){this.Fb||(this.Fb=this.f.createMediaStreamDestination(),this.Gb.connect(this.Fb));return this.Fb.stream}static pe(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Je(a){return a*h}static ne(a){return Math.pow(10,a/20)}static bd(a){return Math.max(Math.min(self.da.ne(a),1),0)}static Be(a){return Math.log(a)/Math.log(10)*20}static Ae(a){return self.da.Be(Math.max(Math.min(a,1),0))}static vg(a,b){return 1-Math.exp(-b*a)}};self.Pa.mb(self.da)}"use strict";function V(h){h.Lb||(h.Lb=h.pc());return h.Lb}
self.Zc=class{constructor(h,a,b,c,f){this.i=h;this.rg=a;this.ua=b;this.P=c;this.og=f;this.Bc="";this.Lb=null}c(){this.Lb=this.i=null}pc(){}V(){return this.i.V()}$b(){return this.rg}Na(){return this.ua}Zb(){return this.P}pa(){return this.og}ea(){}};"use strict";
self.ie=class extends self.Zc{constructor(h,a,b,c,f){super(h,a,b,c,f);this.Bc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.$a=this.ab=null;this.H.addEventListener("canplaythrough",()=>!0);this.fb=this.V().createGain();this.cb=null;this.H.addEventListener("canplay",()=>{this.ab&&(this.ab(),this.$a=this.ab=null);!this.cb&&this.H&&(this.cb=this.V().createMediaElementSource(this.H),this.cb.connect(this.fb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",p=>{console.error(`[Construct 3] Audio '${this.ua}' error: `,p);this.$a&&(this.$a(p),this.$a=this.ab=null)})}c(){this.i.hd(this);this.fb.disconnect();this.fb=null;this.cb.disconnect();this.cb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}pc(){return new Promise((h,a)=>{this.ab=h;this.$a=a;this.H.src=this.ua})}N(){return this.H}ea(){return this.H.duration}};"use strict";
async function W(h){if(h.ra)return h.ra;var a=h.i.A;if("cordova"===a.J&&a.ye(h.ua)&&"file:"===location.protocol)h.ra=await a.Wb(h.ua);else{a=await fetch(h.ua);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);h.ra=await a.arrayBuffer()}}async function X(h){if(h.$)return h.$;h.$=await h.i.oe(h.ra,h.qg);h.ra=null}
self.ke=class extends self.Zc{constructor(h,a,b,c,f,p){super(h,a,b,c,f);this.Bc="webaudio";this.$=this.ra=null;this.qg=!!p}c(){this.i.hd(this);this.$=this.ra=null;super.c()}async pc(){try{await W(this),await X(this)}catch(h){console.error(`[Construct 3] Failed to load audio '${this.ua}': `,h)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let h=0;self.$c=class{constructor(a,b,c){this.i=a;this.K=b;this.Z=c;this.Eb=h++;this.L=this.V().createGain();this.L.connect(this.oa());this.v=null;this.Ya=!1;this.F=!0;this.U=this.ia=this.D=!1;this.jb=1;this.Aa=!1;this.Y=1;a=this.i.Uc;this.Lc=1===a&&!this.pa()||2===a;this.Va=this.fa=-1;this.Sd=!1}c(){this.K=this.i=null;this.v&&(this.v.disconnect(),this.v=null);this.L.disconnect();this.L=null}V(){return this.i.V()}oa(){return this.i.cd(this.Z)}ob(){return this.i.ob()}nb(){return this.Lc?this.i.Gc:
performance.now()/1E3}$b(){return this.K.$b()}Na(){return this.K.Na()}Zb(){return this.K.Zb()}pa(){return this.K.pa()}He(a){this.Z=a}S(){}Vb(){}IsPlaying(){return!this.F&&!this.D&&!this.S()}dd(){return!this.F&&!this.S()}va(){}ea(){return this.K.ea()}Play(){}ka(){}Oa(){}rb(){}ub(a){this.jb=a;this.L.gain.cancelScheduledValues(0);this.Va=-1;this.L.gain.value=this.ac()}qe(a,b,c){if(!this.Aa){a*=this.ob();var f=this.L.gain;f.cancelScheduledValues(0);var p=this.i.Yb();b=p+b;f.setValueAtTime(f.value,p);
f.linearRampToValueAtTime(a,b);this.jb=a;this.Va=b;this.Sd=c}}Db(){this.ub(this.jb)}xa(a){-1!==this.Va&&a>=this.Va&&(this.Va=-1,this.Sd&&this.ka(),this.i.ec("fade-ended",this.Z,this.Eb))}ac(){const a=this.jb*this.ob();return isFinite(a)?a:0}jd(a){a=!!a;this.Aa!==a&&(this.Aa=a,this.Cb())}pb(){return this.i.pb()}Cb(){}hc(){}ld(a){this.Y!==a&&(this.Y=a,this.ya())}ya(){}fc(){}ic(){}sb(a){a=!!a;this.Ya!==a&&((this.Ya=a)?(this.v||(this.v=this.V().createPanner(),this.v.panningModel=this.i.Nd,this.v.distanceModel=
this.i.Ed,this.v.refDistance=this.i.Od,this.v.maxDistance=this.i.Md,this.v.rolloffFactor=this.i.Qd),this.L.disconnect(),this.L.connect(this.v),this.v.connect(this.oa())):(this.v.disconnect(),this.L.disconnect(),this.L.connect(this.oa())))}Ge(a,b,c,f,p,t){this.Ya&&(this.kd(a,b,c),a=self.da.Je,this.v.coneInnerAngle=a(f),this.v.coneOuterAngle=a(p),this.v.coneOuterGain=t)}kd(a,b,c){this.Ya&&(this.v.setPosition(a,b,0),this.v.setOrientation(Math.cos(c),Math.sin(c),0))}Ie(a){this.fa=a}bc(){}Ee(a){const b=
this.v||this.L;b.disconnect();b.connect(a)}Ma(){return{aiid:this.Eb,tag:this.Z,duration:this.ea(),volume:this.jb,isPlaying:this.IsPlaying(),playbackTime:this.va(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.$b(),bufferUrl:"",bufferType:this.Zb(),isMusic:this.pa(),isLooping:this.U,isMuted:this.Aa,resumePosition:this.bc(),pan:this.se()}}qc(a){this.ld(a.playbackRate);this.jd(a.isMuted)}se(){if(!this.v)return null;const a=this.v;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Ce(a){a?(this.sb(!0),a=this.v,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.sb(!1)}}}"use strict";
self.je=class extends self.$c{constructor(h,a,b){super(h,a,b);this.K.fb.connect(this.L);this.K.onended=()=>this.sc()}c(){this.ka();this.K.fb.disconnect();super.c()}N(){return this.K.N()}sc(){this.F=!0;this.fa=-1;this.i.ec("ended",this.Z,this.Eb)}S(){return this.N().ended}Vb(){return this.F?!0:this.S()}va(h){let a=this.N().currentTime;h&&(a*=this.Y);this.U||(a=Math.min(a,this.ea()));return a}Play(h,a,b){const c=this.N();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==h&&(c.loop=h);this.ub(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.K.Na()}' to position '${b}': `,f)}this.i.qa(c);this.D=this.F=!1;this.U=h;this.Y=1}ka(){const h=this.N();h.paused||h.pause();this.i.wa(h);this.F=!0;this.D=!1;this.fa=-1}Oa(){if(!(this.D||this.F||this.S())){var h=this.N();h.paused||h.pause();this.i.wa(h);this.D=!0}}rb(){!this.D||this.F||this.S()||(this.i.qa(this.N()),this.D=!1)}Cb(){this.N().muted=this.Aa||this.pb()}hc(h){h=!!h;
this.U!==h&&(this.U=h,this.N().loop=h)}ya(){let h=this.Y;this.Lc&&(h*=this.i.Tb);try{this.N().playbackRate=h}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${h}':`,a)}}fc(h){if(!this.F&&!this.S())try{this.N().currentTime=h}catch(a){console.warn(`[Construct 3] Error seeking audio to '${h}': `,a)}}bc(){return this.va()}ic(h){h?this.IsPlaying()?(this.N().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.qa(this.N()),this.ia=!1)}};"use strict";
function Y(h){h.j&&h.j.disconnect();h.j=null;h.Ra=null}
self.le=class extends self.$c{constructor(h,a,b){super(h,a,b);this.j=null;this.Ob=c=>this.sc(c);this.Hc=!0;this.Ra=null;this.M=this.Sb=0;this.Pc=1}c(){this.ka();Y(this);this.Ob=null;super.c()}sc(h){this.D||this.ia||h.target!==this.Ra||(this.F=this.Hc=!0,this.fa=-1,Y(this),this.i.ec("ended",this.Z,this.Eb))}S(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Hc}Vb(){return!this.j||this.F?!0:this.S()}va(h){let a;a=this.D?this.M:this.nb()-this.Sb;h&&(a*=this.Y);this.U||(a=Math.min(a,this.ea()));return a}Play(h,
a,b,c){this.Pc=1;this.ub(a);Y(this);this.j=this.V().createBufferSource();this.j.buffer=this.K.$;this.j.connect(this.L);this.Ra=this.j;this.j.onended=this.Ob;this.j.loop=h;this.j.start(c,b);this.D=this.F=this.Hc=!1;this.U=h;this.Y=1;this.Sb=this.nb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(h){}this.F=!0;this.D=!1;this.fa=-1}Oa(){this.D||this.F||this.S()||(this.M=this.va(!0),this.U&&(this.M%=this.ea()),this.D=!0,this.j.stop(0))}rb(){!this.D||this.F||this.S()||(Y(this),this.j=this.V().createBufferSource(),
this.j.buffer=this.K.$,this.j.connect(this.L),this.Ra=this.j,this.j.onended=this.Ob,this.j.loop=this.U,this.Db(),this.ya(),this.Sb=this.nb()-this.M/(this.Y||.001),this.j.start(0,this.M),this.D=!1)}ac(){return super.ac()*this.Pc}Cb(){this.Pc=this.Aa||this.pb()?0:1;this.Db()}hc(h){h=!!h;this.U!==h&&(this.U=h,this.j&&(this.j.loop=h))}ya(){let h=this.Y;this.Lc&&(h*=this.i.Tb);this.j&&(this.j.playbackRate.value=h)}fc(h){this.F||this.S()||(this.D?this.M=h:(this.Oa(),this.M=h,this.rb()))}bc(){return this.M}ic(h){h?
this.IsPlaying()?(this.ia=!0,this.M=this.va(!0),this.U&&(this.M%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(Y(this),this.j=this.V().createBufferSource(),this.j.buffer=this.K.$,this.j.connect(this.L),this.Ra=this.j,this.j.onended=this.Ob,this.j.loop=this.U,this.Db(),this.ya(),this.Sb=this.nb()-this.M/(this.Y||.001),this.j.start(0,this.M),this.ia=!1)}qc(h){super.qc(h);this.M=h.resumePosition}};"use strict";
{class h{constructor(a){this.i=a;this.f=a.V();this.Hd=-1;this.P=this.Z="";this.g=null}c(){this.f=null}Uf(a){this.Hd=a}bg(a){this.Z=a}o(){return this.f.createGain()}O(){}R(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var p=this.f.currentTime;f+=p;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,p);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,p),a.exponentialRampToValueAtTime(b,f)}}}Ma(){return{type:this.P,tag:this.Z,params:this.g}}}
self.ce=class extends h{constructor(a,b,c,f,p,t,d){super(a);this.P="filter";this.g=[b,c,f,p,t,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=f;this.u.Q.value=p;this.u.gain.vlaue=t;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,f)}}};self.ae=class extends h{constructor(a,b,c,f){super(a);this.P="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.bb=this.o();this.T=this.f.createDelay(b);this.T.delayTime.value=b;this.Ua=this.o();this.Ua.gain.value=c;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b);this.bb.connect(this.T);this.T.connect(this.Ua);this.Ua.connect(this.bb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.bb.disconnect();this.T.disconnect();this.Ua.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){const p=self.da.bd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=p(b);this.m(this.Ua.gain,p(b),c,f);break;case 5:this.g[0]=b,this.m(this.T.delayTime,b,c,f)}}};self.$d=class extends h{constructor(a,b,c,f){super(a);this.P="convolution";this.g=[c,f];this.Cd=this.Bd="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Ta=this.f.createConvolver();this.Ta.normalize=c;this.Ta.buffer=b;this.l.connect(this.Ta);this.l.connect(this.a);this.Ta.connect(this.b)}c(){this.l.disconnect();this.Ta.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}Qf(a,b){this.Bd=a;this.Cd=b}Ma(){const a=
super.Ma();a.bufferOriginalUrl=this.Bd;a.bufferUrl="";a.bufferType=this.Cd;return a}};self.de=class extends h{constructor(a,b,c,f,p,t){super(a);this.P="flanger";this.g=[b,c,f,p,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.Wa=this.o();this.Wa.gain.value=p;this.T=this.f.createDelay(b+c);this.T.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.G=this.o();this.G.gain.value=c;this.l.connect(this.T);this.l.connect(this.a);
this.T.connect(this.b);this.T.connect(this.Wa);this.Wa.connect(this.T);this.s.connect(this.G);this.G.connect(this.T.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.T.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.Wa.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.Wa.gain,b/100,c,f)}}};self.fe=class extends h{constructor(a,b,c,f,p,t,d){super(a);this.P="phaser";this.g=[b,c,f,p,t,d];this.l=this.o();this.a=this.o();this.a.gain.value=1-d/2;this.b=this.o();this.b.gain.value=d/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=t;this.G=this.o();this.G.gain.value=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.G.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,f)}}};self.ee=class extends h{constructor(a,b){super(a);this.P="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,c,f){const p=self.da.bd;switch(a){case 4:this.g[0]=p(b),this.m(this.h.gain,p(b),c,f)}}};self.he=class extends h{constructor(a,b,c){super(a);this.P="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=c/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,c,f);this.m(this.G.gain.value,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.ge=class extends h{constructor(a,b,c){super(a);this.P="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.ib=this.o();
this.ib.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.ib.gain);this.s.start(0);this.l.connect(this.ib);this.l.connect(this.a);this.ib.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.ib.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}R(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,c,f);this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.be=class extends h{constructor(a,b,c,f,p,t){super(a);this.P="distortion";this.g=[b,c,f,p,t];this.l=this.o();this.Qb=this.o();this.Pb=this.o();this.Rf(f,p);this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.Ub=this.f.createWaveShaper();this.Ec=new Float32Array(65536);this.$e(b,c);this.Ub.curve=this.Ec;this.l.connect(this.Qb);this.l.connect(this.a);this.Qb.connect(this.Ub);
this.Ub.connect(this.Pb);this.Pb.connect(this.b)}c(){this.l.disconnect();this.Qb.disconnect();this.Ub.disconnect();this.Pb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Rf(a,b){.01>a&&(a=.01);this.Qb.gain.value=a;this.Pb.gain.value=Math.pow(1/a,.6)*b}$e(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.dg(f,a,b);this.Ec[32768+c]=f;this.Ec[32768-c-1]=-f}}dg(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.da.vg(f-b,1/c))*(0>a?-1:1)}R(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.Zd=class extends h{constructor(a,b,c,f,p,t){super(a);this.P="compressor";this.g=[b,c,f,p,t];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=p;this.h.release.value=t}c(){this.h.disconnect();super.c()}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.Yd=class extends h{constructor(a,b,c){super(a);this.P="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Fd=new Float32Array(this.h.frequencyBinCount);this.Rd=new Uint8Array(b);this.Pd=this.Da=0;this.i.Ke(this)}c(){this.i.Kf(this);this.h.disconnect();super.c()}xa(){this.h.getFloatFrequencyData(this.Fd);this.h.getByteTimeDomainData(this.Rd);const a=this.h.fftSize;let b=this.Da=0;for(var c=0;c<a;++c){let f=(this.Rd[c]-128)/128;0>f&&(f=-f);
this.Da<f&&(this.Da=f);b+=f*f}c=self.da.Ae;this.Da=c(this.Da);this.Pd=c(Math.sqrt(b/a))}R(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}re(){return{tag:this.Z,index:this.Hd,peak:this.Da,rms:this.Pd,binCount:this.h.frequencyBinCount,freqBins:this.Fd}}}}"use strict";self.Pa.mb(class extends self.La{constructor(h){super(h,"mouse");A(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
function Z(h){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>v(h,"sw-message",a.data))}
function aa(h){h=h.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(h).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(h):screen.webkitLockOrientation?a=screen.webkitLockOrientation(h):screen.mozLockOrientation?a=screen.mozLockOrientation(h):screen.msLockOrientation&&(a=screen.msLockOrientation(h));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.Pa.mb(class extends self.La{constructor(h){super(h,"browser");this.J="";B(this,[["get-initial-state",a=>{this.J=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Z(this)],
["alert",a=>this.rc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.xc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>aa(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a?window.open(b,"_blank"):this.Ig||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",
a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{v(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{v(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{v(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{v(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;v(this,"backbutton")})}rc(h){alert(h.message)}xc(h){h=h.isFocus;if("nwjs"===this.J){const a="nwjs"===this.J?nw.Window.get():null;h?a.focus():a.blur()}else h?window.focus():window.blur()}});